services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    depends_on:
      - php
    networks:
      - symfony
    ports:
      - "80:80"

  php:
    image: php:8.2-fpm
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - symfony

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  mysql_data:
